server:
  port: 5002

spring:
  application:
    name: TASK-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/task_service
    username: root
    password: Meenu@123
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health, info  # Expose only health and info endpoints
  endpoint:
    health:
      show-details: always  # Show detailed health info
